dataset:
  name: mnist
  num_classes: 10
  image_size: 28
  pre_size: 28

  interpolation: bilinear
  normalization_type: mnist

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: /data/saiful/openood_datasets/images_classic/
    imglist_pth: /data/saiful/openood_datasets/benchmark_imglist/mnist/train_mnist.txt
    batch_size: 128 #00
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: /data/saiful/openood_datasets/images_classic/
    imglist_pth: /data/saiful/openood_datasets/benchmark_imglist/mnist/val_mnist.txt
    batch_size: 200 #00
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: /data/saiful/openood_datasets/images_classic/
    imglist_pth: /data/saiful/openood_datasets/benchmark_imglist/mnist/test_mnist.txt
    batch_size: 200 #00
    shuffle: False


# dataset:
#   name: mnist
#   num_classes: 10
#   image_size: 28
#   pre_size: 28

#   interpolation: bilinear
#   normalization_type: mnist

#   num_workers: '@{num_workers}'
#   num_gpus: '@{num_gpus}'
#   num_machines: '@{num_machines}'

#   split_names: [train, val, test]

#   train:
#     dataset_class: ImglistDataset
#     data_dir: /home/magesh/data-magesh/images_classic/
#     imglist_pth: /home/magesh/data-magesh/benchmark_imglist/mnist/train_mnist.txt
#     batch_size: 128000
#     shuffle: True
#   val:
#     dataset_class: ImglistDataset
#     data_dir: /home/magesh/data-magesh/images_classic/
#     imglist_pth: /home/magesh/data-magesh/benchmark_imglist/mnist/val_mnist.txt
#     batch_size: 200000
#     shuffle: False
#   test:
#     dataset_class: ImglistDataset
#     data_dir: /home/magesh/data-magesh//images_classic/
#     imglist_pth: /home/magesh/data-magesh//benchmark_imglist/mnist/test_mnist.txt
#     batch_size: 200000
#     shuffle: False
