dataset:
  name: imagenet
  num_classes: 1000
  pre_size: 256
  image_size: 224

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]
  # split_names: [val, test]

  train:
     dataset_class: ImglistDataset
     # data_dir: ./data/images_largescale/
     data_dir: /data/saiful/imagenet_datasets2/imagenet_full_dataset/ILSVRC/Data/CLS-LOC/train/
     imglist_pth: /data/saiful/openood_datasets/benchmark_imglist/imagenet/train_imagenet.txt
     batch_size: 256
     shuffle: False
  val:
    dataset_class: ImglistDataset
    data_dir: /data/saiful/openood_datasets/images_largescale/
    imglist_pth: /data/saiful/openood_datasets/benchmark_imglist/imagenet/val_imagenet.txt
    batch_size: 256 # 32
    shuffle: True
  test:
    dataset_class: ImglistDataset
    data_dir: /data/saiful/openood_datasets/images_largescale/
    imglist_pth: /data/saiful/openood_datasets/benchmark_imglist/imagenet/test_imagenet.txt
    batch_size: 256 # 32
    shuffle: True

